blueprint:
  name: Actions for 2-Button Homematic(IP) HmIP-WRCC2 device
  description: When a button is pressed, the defined actions will be executed. Please
    keep in mind, that long-press actions might be executed multiple times, according
    to your configured minimum duration for long press. This can be configured in
    your CCU.
    Tested with HmIP-WRCC2. Should work with other device too.
    v2022-10-28
  domain: automation
  source_url: https://github.com/smeagel73/TestGround/blob/master/HA_Blueprint_HmIP-WRCC2.yaml
  input:
    remote:
      name: 2-Button Device
      description: Please select a 2-Button device of your Homematic(IP) Local integration.
      selector:
        device:
          integration: homematicip_local
    action_1_short:
      name: Action
      description: 1-Button, Short Press
      default: []
      selector:
        action: {}
    action_1_long:
      name: Action
      description: 1-Button, Long Press
      default: []
      selector:
        action: {}
    action_2_short:
      name: Action
      description: 2-Button, Short Press
      default: []
      selector:
        action: {}
    action_2_long:
      name: Action
      description: 2-Button, Long Press
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: homematic.keypress
  event_data:
    device_id: !input 'remote'
condition: []
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 1 }}'
    sequence: !input 'action_1_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 1 }}'
    sequence: !input 'action_1_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 2 }}'
    sequence: !input 'action_2_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 2 }}'
    sequence: !input 'action_2_long'
mode: parallel
max: 10
